#! /bin/bash

mount -t proc /proc /proc
mount -t sysfs /sys /sys

rm -rf mytmpfs
mkdir /mytempfs
mount -t tmpfs -o size=4g tmpfs /mytmpfs

echo "****************************************"
echo Linux 5.14 Kernel withc cpuidle modified Has Successfully Booted

# To keep track of which kernel get booted 
uname -a
echo "****************************************"

#Calling shutdown to exit QEMU
./shutdown
